language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
branches:
  only:
    - master
    - gh-pages
after_success:
  - 'git subtree push --prefix dist origin gh-pages'
